List<String> items = [
  "Pop",
  "K-Pop",
  "Rock",
  "Ballad",
  "RnB",
  "J-Pop",
  "I-Pop",
  "Indie",
  "Ahaha",
  "Madeleine Carney",
  "Kaydence Trujillo",
  "Zion Dickson",
  "Laney Scott",
  "Kyleigh Jordan",
  "Teagan Roach",
  "Gilbert Rodgers",
  "Jaylan Ferrell",
  "Harley Fry",
  "Brittany Dickson",
  "Paulina Stanton",
  "Tyrell Delgado",
  "Brayden Conner",
  "Erin Stewart",
  "Justus Buck",
  "Jaycee Hancock",
  "Landon Hutchinson",
  "Maxim Schmitt",
  "Aaron Mccarthy",
  "Mikaela West",
  "Alexis Wolf",
  "Isabel Norman",
  "Delilah Bishop",
  "Brock Michael",
  "Aldo Brady",
  "Renee Harrell",
  "Conrad Reed",
  "Griffin Huerta",
  "Aditya Morgan",
  "Raegan Prince",
  "Rayna Curry",
];